### ISSUE TITLE
Update blockly to recent version

### ISSUE THREAD

**Issue by q383186554** [chekoduadarsh/BlocklyML#113]
Hi I am using this project. Could you update blockly version to recent? And could you tell me how to develop module myself?

**Comment by q383186554** [comment]
I have done it myself. thanks anyway

**Comment by q383186554** [comment]
Hi dear author. Could you send me the file of the blocks like below? 


Blockly.Blocks['none'] = {
  init: function() {
    this.setColour(65);
    this.appendDummyInput()
        .appendField("None")
    this.setOutput(true);
    this.setTooltip('');
  }
};
Blockly.Python['none'] = function(block) {
  var code = "None";
  return [code, Blockly.Python.ORDER_NONE];
};

**Comment by chekoduadarsh** [comment]
@q383186554 

Sorry for the delay. 
**static/js/python_ML.js** to design python output code
**static/js/blocks_ML.js** to design the blocks

**Comment by q383186554** [comment]
> @q383186554 
> 
> Sorry for the delay. 
> **static/js/python_ML.js** to design python output code
> **static/js/blocks_ML.js** to design the blocks

hi i saw the code in them but the blocks contain basic blocks such as logic and I want to separate them. I use vue3 now. do you have the block xml file?

**Comment by q383186554** [comment]
could you teach me how to make blocks and build them

**Comment by chekoduadarsh** [comment]
@q383186554 

you can split them however you want. Make sure that you import them properly. To make new blocks you need to add code to blockls_ML.js. Then its output code to python_ML (for python)

I referred to this to create custom blocks: https://developers.google.com/blockly/guides/create-custom-blocks/overview

Google has better documentation on this than me 😃

**Comment by q383186554** [comment]
> @q383186554 
> 
> you can split them however you want. Make sure that you import them properly. To make new blocks you need to add code to blockls_ML.js. Then its output code to python_ML (for python)
> 
> I referred to this to create custom blocks: https://developers.google.com/blockly/guides/create-custom-blocks/overview
> 
> Google has better documentation on this than me 😃 
> 

thanks a lot. I will try it out
